-- MySQL Script generated by MySQL Workbench
-- 10/14/15 11:52:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema 4pt
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 4pt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `4pt` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `4pt` ;

-- -----------------------------------------------------
-- Table `4pt`.`companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `4pt`.`companies` ;

CREATE TABLE IF NOT EXISTS `4pt`.`companies` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `address` VARCHAR(128) NOT NULL,
  `phone` VARCHAR(16) NOT NULL,
  `language` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`id`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4pt`.`people`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `4pt`.`people` ;

CREATE TABLE IF NOT EXISTS `4pt`.`people` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` INT UNSIGNED NOT NULL,
  `first_name` VARCHAR(32) NOT NULL,
  `middle_name` VARCHAR(32) NULL,
  `last_name` VARCHAR(32) NULL,
  `email` VARCHAR(254) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `phone` VARCHAR(16) NULL,
  `habilities` VARCHAR(64) NULL,
  `capabilities` VARCHAR(64) NULL,
  `roles` VARCHAR(16) NULL,
  PRIMARY KEY (`id`) ,
  UNIQUE (email),
  CONSTRAINT `fk_people_companies`
    FOREIGN KEY (`company_id`)
    REFERENCES `4pt`.`companies` (`id`))
ENGINE = InnoDB;

CREATE INDEX `fk_people_companies_idx` ON `4pt`.`people` (`company_id` ASC) ;


-- -----------------------------------------------------
-- Table `4pt`.`projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `4pt`.`projects` ;

CREATE TABLE IF NOT EXISTS `4pt`.`projects` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` INT UNSIGNED NOT NULL,
  `title` VARCHAR(64) NOT NULL,
  `acronym` VARCHAR(16) NOT NULL,
  `product_type` INT NOT NULL,
  `level` INT NOT NULL,
  `template` INT UNSIGNED NULL,
  `roles` VARCHAR(64) NULL,
  `people` VARCHAR(256) NULL,

  PRIMARY KEY (`id`) ,
  CONSTRAINT `fk_project_companies1`
    FOREIGN KEY (`company_id`)
    REFERENCES `4pt`.`companies` (`id`))
ENGINE = InnoDB;

CREATE INDEX `fk_project_companies1_idx` ON `4pt`.`projects` (`company_id` ASC) ;


-- -----------------------------------------------------
-- Table `4pt`.`templates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `4pt`.`templates` ;

CREATE TABLE IF NOT EXISTS `4pt`.`templates` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` INT UNSIGNED NOT NULL,
  `used_times` INT UNSIGNED NULL DEFAULT 0,
  `name` VARCHAR(64) NOT NULL,
  `scope` TINYINT(1) NULL,
  `communication_plan` TINYINT(1) NULL,
  `general_purpose` TINYINT(1) NULL,
  `specific_objectives` TINYINT(1) NULL,
  `justification` TINYINT(1) NULL,
  `tool` TINYINT(1) NULL,
  `communication_type` TINYINT(1) NULL,
  `roles` TINYINT(1) NULL,
  `risk` TINYINT(1) NULL,
  `impact` TINYINT(1) NULL,
  `answer` TINYINT(1) NULL,
  `testing` TINYINT(1) NULL,
  `people` TINYINT(1) NULL,
  `timetable` TINYINT(1) NULL,
  PRIMARY KEY (`id`) ,
  CONSTRAINT `fk_templates_companies1`
    FOREIGN KEY (`company_id`)
    REFERENCES `4pt`.`companies` (`id`))
ENGINE = InnoDB;

CREATE INDEX `fk_templates_companies1_idx` ON `4pt`.`templates` (`company_id` ASC) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;