-- MySQL Script generated by MySQL Workbench
-- 03/03/17 18:53:11
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema 4pt
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `4pt` ;

-- -----------------------------------------------------
-- Schema 4pt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `4pt` DEFAULT CHARACTER SET utf8 ;
USE `4pt` ;

-- -----------------------------------------------------
-- Table `4pt`.`companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `4pt`.`companies` ;

CREATE TABLE IF NOT EXISTS `4pt`.`companies` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` TEXT NOT NULL,
  `address` TEXT NOT NULL,
  `phone` TEXT NOT NULL,
  `language` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4pt`.`people`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `4pt`.`people` ;

CREATE TABLE IF NOT EXISTS `4pt`.`people` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` INT UNSIGNED NOT NULL,
  `first_name` TEXT NOT NULL,
  `middle_name` TEXT NULL DEFAULT NULL,
  `last_name` TEXT NULL DEFAULT NULL,
  `email` TEXT NOT NULL,
  `password` TEXT NOT NULL,
  `phone` TEXT NULL DEFAULT NULL,
  `habilities` TEXT NULL DEFAULT NULL,
  `capabilities` TEXT NULL DEFAULT NULL,
  `roles` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_people_companies_idx` (`company_id` ASC),
  CONSTRAINT `fk_people_companies`
    FOREIGN KEY (`company_id`)
    REFERENCES `4pt`.`companies` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4pt`.`projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `4pt`.`projects` ;

CREATE TABLE IF NOT EXISTS `4pt`.`projects` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` INT UNSIGNED NOT NULL,
  `title` TEXT NOT NULL,
  `acronym` TEXT NOT NULL,
  `product_type` INT NOT NULL,
  `level` INT NOT NULL,
  `template` INT UNSIGNED NULL DEFAULT NULL,
  `roles` TEXT NULL DEFAULT NULL,
  `people` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_project_companies1_idx` (`company_id` ASC),
  CONSTRAINT `fk_project_companies1`
    FOREIGN KEY (`company_id`)
    REFERENCES `4pt`.`companies` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4pt`.`templates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `4pt`.`templates` ;

CREATE TABLE IF NOT EXISTS `4pt`.`templates` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` INT UNSIGNED NOT NULL,
  `used_times` INT UNSIGNED NULL DEFAULT 0,
  `name` TEXT NOT NULL,
  `work_statement` TINYINT(1) NULL DEFAULT NULL,
  `delivery_instructions` TINYINT(1) NULL DEFAULT NULL,
  `tasks` TINYINT(1) NULL DEFAULT NULL,
  `risks` TINYINT(1) NULL DEFAULT NULL,
  `minutes` TINYINT(1) NULL DEFAULT NULL,
  `progress_report` TINYINT(1) NULL DEFAULT NULL,
  `corrective_actions` TINYINT(1) NULL DEFAULT NULL,
  `software_requirements` TINYINT(1) NULL DEFAULT NULL,
  `user_manual` TINYINT(1) NULL DEFAULT NULL,
  `software_design` TINYINT(1) NULL DEFAULT NULL,
  `operation_manual` TINYINT(1) NULL DEFAULT NULL,
  `maintenance_manual` TINYINT(1) NULL DEFAULT NULL,
  `software_components` TINYINT(1) NULL DEFAULT NULL,
  `test_reports` TINYINT(1) NULL DEFAULT NULL,
  `act_of_acceptance` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_templates_companies1_idx` (`company_id` ASC),
  CONSTRAINT `fk_templates_companies1`
    FOREIGN KEY (`company_id`)
    REFERENCES `4pt`.`companies` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4pt`.`processes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `4pt`.`processes` ;

CREATE TABLE IF NOT EXISTS `4pt`.`processes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_processes_projects1_idx` (`project_id` ASC),
  CONSTRAINT `fk_processes_projects1`
    FOREIGN KEY (`project_id`)
    REFERENCES `4pt`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4pt`.`work_statement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `4pt`.`work_statement` ;

CREATE TABLE IF NOT EXISTS `4pt`.`work_statement` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `process_id` INT UNSIGNED NOT NULL,
  `product_description` TEXT NULL DEFAULT NULL,
  `scope` TEXT NULL DEFAULT NULL,
  `objectives` TEXT NULL DEFAULT NULL,
  `deliverables` TEXT NULL DEFAULT NULL,
  `sent` TINYINT(1) NULL DEFAULT NULL,
  `project_manager_validated` TINYINT(1) NULL DEFAULT NULL,
  `technical_leader_validated` TINYINT(1) NULL DEFAULT NULL,
  `change_request` TINYINT(1) NULL DEFAULT NULL,
  `change_request_details` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_work_statement_process1_idx` (`process_id` ASC),
  CONSTRAINT `fk_work_statement_process1`
    FOREIGN KEY (`process_id`)
    REFERENCES `4pt`.`processes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4pt`.`project_plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `4pt`.`project_plan` ;

CREATE TABLE IF NOT EXISTS `4pt`.`project_plan` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `process_id` INT UNSIGNED NOT NULL,
  `sent` TINYINT(1) NULL DEFAULT NULL,
  `project_manager_validated` TINYINT(1) NULL DEFAULT NULL,
  `technical_leader_validated` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_project_plan_processes1_idx` (`process_id` ASC),
  CONSTRAINT `fk_project_plan_processes1`
    FOREIGN KEY (`process_id`)
    REFERENCES `4pt`.`processes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4pt`.`delivery_instructions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `4pt`.`delivery_instructions` ;

CREATE TABLE IF NOT EXISTS `4pt`.`delivery_instructions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_plan_id` INT UNSIGNED NOT NULL,
  `release_requirements` TEXT NULL DEFAULT NULL,
  `delivery_requirements` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_delivery_instructions_project_plan1_idx` (`project_plan_id` ASC),
  CONSTRAINT `fk_delivery_instructions_project_plan1`
    FOREIGN KEY (`project_plan_id`)
    REFERENCES `4pt`.`project_plan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4pt`.`tasks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `4pt`.`tasks` ;

CREATE TABLE IF NOT EXISTS `4pt`.`tasks` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_plan_id` INT UNSIGNED NOT NULL,
  `title` TEXT NULL DEFAULT NULL,
  `task` TEXT NULL DEFAULT NULL,
  `duration` DOUBLE NULL DEFAULT NULL,
  `start_date` DATETIME NULL DEFAULT NULL,
  `resources` DOUBLE NULL DEFAULT NULL,
  `people_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tasks_project_plan1_idx` (`project_plan_id` ASC),
  INDEX `fk_tasks_people1_idx` (`people_id` ASC),
  CONSTRAINT `fk_tasks_project_plan1`
    FOREIGN KEY (`project_plan_id`)
    REFERENCES `4pt`.`project_plan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tasks_people1`
    FOREIGN KEY (`people_id`)
    REFERENCES `4pt`.`people` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4pt`.`minutes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `4pt`.`minutes` ;

CREATE TABLE IF NOT EXISTS `4pt`.`minutes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_plan_id` INT UNSIGNED NOT NULL,
  `purpose` TEXT NULL DEFAULT NULL,
  `assistants` TEXT NULL DEFAULT NULL,
  `date` DATETIME NULL DEFAULT NULL,
  `place` TEXT NULL DEFAULT NULL,
  `previous_minute_id` INT UNSIGNED NULL,
  `issues_raised` TEXT NULL DEFAULT NULL,
  `open_issues` TEXT NULL DEFAULT NULL,
  `agreements` TEXT NULL DEFAULT NULL,
  `next_meeting` DATETIME NULL DEFAULT NULL,
  `client_validated` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_minutes_project_plan1_idx` (`project_plan_id` ASC),
  INDEX `fk_minutes_minutes1_idx` (`previous_minute_id` ASC),
  CONSTRAINT `fk_minutes_project_plan1`
    FOREIGN KEY (`project_plan_id`)
    REFERENCES `4pt`.`project_plan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_minutes_minutes1`
    FOREIGN KEY (`previous_minute_id`)
    REFERENCES `4pt`.`minutes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4pt`.`progress_reports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `4pt`.`progress_reports` ;

CREATE TABLE IF NOT EXISTS `4pt`.`progress_reports` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `process_id` INT UNSIGNED NOT NULL,
  `task_status` TEXT NULL DEFAULT NULL,
  `results_status` TEXT NULL DEFAULT NULL,
  `resources_status` TEXT NULL DEFAULT NULL,
  `costs_status` TEXT NULL DEFAULT NULL,
  `calendar_status` TEXT NULL DEFAULT NULL,
  `risks_status` TEXT NULL DEFAULT NULL,
  `deviations_record` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_progress_reports_processes1_idx` (`process_id` ASC),
  CONSTRAINT `fk_progress_reports_processes1`
    FOREIGN KEY (`process_id`)
    REFERENCES `4pt`.`processes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4pt`.`corrective_actions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `4pt`.`corrective_actions` ;

CREATE TABLE IF NOT EXISTS `4pt`.`corrective_actions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `process_id` INT UNSIGNED NOT NULL,
  `problem` TEXT NULL DEFAULT NULL,
  `solution` TEXT NULL DEFAULT NULL,
  `corrective_actions` TEXT NULL DEFAULT NULL,
  `responsible_id` INT UNSIGNED NULL,
  `open_date` DATETIME NULL DEFAULT NULL,
  `close_date` DATETIME NULL DEFAULT NULL,
  `complete` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_corrective_actions_people1_idx` (`responsible_id` ASC),
  INDEX `fk_corrective_actions_processes1_idx` (`process_id` ASC),
  CONSTRAINT `fk_corrective_actions_people1`
    FOREIGN KEY (`responsible_id`)
    REFERENCES `4pt`.`people` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_corrective_actions_processes1`
    FOREIGN KEY (`process_id`)
    REFERENCES `4pt`.`processes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4pt`.`software_requirements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `4pt`.`software_requirements` ;

CREATE TABLE IF NOT EXISTS `4pt`.`software_requirements` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `process_id` INT UNSIGNED NOT NULL,
  `introduction` TEXT NULL DEFAULT NULL,
  `functionality` TEXT NULL DEFAULT NULL,
  `functionality_file` TEXT NULL DEFAULT NULL,
  `user_interface` TEXT NULL DEFAULT NULL,
  `user_interface_file` TEXT NULL DEFAULT NULL,
  `external_interfaces` TEXT NULL DEFAULT NULL,
  `external_interfaces_file` TEXT NULL DEFAULT NULL,
  `reliability` TEXT NULL DEFAULT NULL,
  `reliability_file` TEXT NULL DEFAULT NULL,
  `efficiency` TEXT NULL DEFAULT NULL,
  `efficiency_file` TEXT NULL DEFAULT NULL,
  `maintenance` TEXT NULL DEFAULT NULL,
  `maintenance_file` TEXT NULL DEFAULT NULL,
  `portability` TEXT NULL DEFAULT NULL,
  `portability_file` TEXT NULL DEFAULT NULL,
  `limitations` TEXT NULL DEFAULT NULL,
  `limitations_file` TEXT NULL DEFAULT NULL,
  `interoperability` TEXT NULL DEFAULT NULL,
  `interoperability_file` TEXT NULL DEFAULT NULL,
  `reuse` TEXT NULL DEFAULT NULL,
  `reuse_file` TEXT NULL DEFAULT NULL,
  `legal` TEXT NULL DEFAULT NULL,
  `legal_file` TEXT NULL DEFAULT NULL,
  `sent` TINYINT(1) NULL DEFAULT NULL,
  `project_manager_validated` TINYINT(1) NULL DEFAULT NULL,
  `technical_leader_validated` TINYINT(1) NULL DEFAULT NULL,
  `change_request` TINYINT(1) NULL DEFAULT NULL,
  `change_request_details` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_software_requirements_processes1_idx` (`process_id` ASC),
  CONSTRAINT `fk_software_requirements_processes1`
    FOREIGN KEY (`process_id`)
    REFERENCES `4pt`.`processes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4pt`.`design_restrictions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `4pt`.`design_restrictions` ;

CREATE TABLE IF NOT EXISTS `4pt`.`design_restrictions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `software_requirements_id` INT UNSIGNED NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_design_restrictions_software_requirements1_idx` (`software_requirements_id` ASC),
  CONSTRAINT `fk_design_restrictions_software_requirements1`
    FOREIGN KEY (`software_requirements_id`)
    REFERENCES `4pt`.`software_requirements` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4pt`.`functionality`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `4pt`.`functionality` ;

CREATE TABLE IF NOT EXISTS `4pt`.`functionality` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `software_requirements_id` INT UNSIGNED NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_functionality_software_requirements1_idx` (`software_requirements_id` ASC),
  CONSTRAINT `fk_functionality_software_requirements1`
    FOREIGN KEY (`software_requirements_id`)
    REFERENCES `4pt`.`software_requirements` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4pt`.`software_design`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `4pt`.`software_design` ;

CREATE TABLE IF NOT EXISTS `4pt`.`software_design` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `process_id` INT UNSIGNED NOT NULL,
  `high_lvl_design` TEXT NULL DEFAULT NULL,
  `high_lvl_design_file` TEXT NULL DEFAULT NULL,
  `low_lvl_design` TEXT NULL DEFAULT NULL,
  `low_lvl_design_file` TEXT NULL DEFAULT NULL,
  `sent` TINYINT(1) NULL DEFAULT NULL,
  `project_manager_validated` TINYINT(1) NULL DEFAULT NULL,
  `technical_leader_validated` TINYINT(1) NULL DEFAULT NULL,
  `change_request` TINYINT(1) NULL DEFAULT NULL,
  `change_request_details` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_software_design_processes1_idx` (`process_id` ASC),
  CONSTRAINT `fk_software_design_processes1`
    FOREIGN KEY (`process_id`)
    REFERENCES `4pt`.`processes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4pt`.`traceability_record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `4pt`.`traceability_record` ;

CREATE TABLE IF NOT EXISTS `4pt`.`traceability_record` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `process_id` INT UNSIGNED NOT NULL,
  `traceability_recordcol` TEXT NULL DEFAULT NULL,
  `traceability_recordcol1` VARCHAR(45) NULL DEFAULT NULL,
  `sent` TINYINT(1) NULL DEFAULT NULL,
  `project_manager_validated` TINYINT(1) NULL DEFAULT NULL,
  `technical_leader_validated` TINYINT(1) NULL DEFAULT NULL,
  `change_request` TINYINT(1) NULL DEFAULT NULL,
  `change_request_details` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_traceability_record_processes1_idx` (`process_id` ASC),
  CONSTRAINT `fk_traceability_record_processes1`
    FOREIGN KEY (`process_id`)
    REFERENCES `4pt`.`processes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4pt`.`operation_manual`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `4pt`.`operation_manual` ;

CREATE TABLE IF NOT EXISTS `4pt`.`operation_manual` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `process_id` INT UNSIGNED NOT NULL,
  `operation_criteria` TEXT NULL DEFAULT NULL,
  `operative_enviroment` TEXT NULL DEFAULT NULL,
  `security_alerts` TEXT NULL DEFAULT NULL,
  `deployment_sequence` TEXT NULL DEFAULT NULL,
  `faq` TEXT NULL DEFAULT NULL,
  `aditional_sources` TEXT NULL DEFAULT NULL,
  `aditional_sources_file` TEXT NULL DEFAULT NULL,
  `security_certification` TEXT NULL DEFAULT NULL,
  `guaranty` TEXT NULL DEFAULT NULL,
  `sent` TINYINT(1) NULL DEFAULT NULL,
  `project_manager_validated` TINYINT(1) NULL DEFAULT NULL,
  `technical_leader_validated` TINYINT(1) NULL DEFAULT NULL,
  `change_request` TINYINT(1) NULL DEFAULT NULL,
  `change_request_details` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_operation_manual_processes1_idx` (`process_id` ASC),
  CONSTRAINT `fk_operation_manual_processes1`
    FOREIGN KEY (`process_id`)
    REFERENCES `4pt`.`processes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4pt`.`maintenance_manual`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `4pt`.`maintenance_manual` ;

CREATE TABLE IF NOT EXISTS `4pt`.`maintenance_manual` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `process_id` INT UNSIGNED NOT NULL,
  `enviroment` TEXT NULL DEFAULT NULL,
  `enviroment_file` TEXT NULL DEFAULT NULL,
  `sent` TINYINT(1) NULL DEFAULT NULL,
  `project_manager_validated` TINYINT(1) NULL DEFAULT NULL,
  `technical_leader_validated` TINYINT(1) NULL DEFAULT NULL,
  `change_request` TINYINT(1) NULL DEFAULT NULL,
  `change_request_details` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_maintenance_manual_processes1_idx` (`process_id` ASC),
  CONSTRAINT `fk_maintenance_manual_processes1`
    FOREIGN KEY (`process_id`)
    REFERENCES `4pt`.`processes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4pt`.`software_component`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `4pt`.`software_component` ;

CREATE TABLE IF NOT EXISTS `4pt`.`software_component` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `process_id` INT UNSIGNED NOT NULL,
  `name` TEXT NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `file` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_software_component_processes1_idx` (`process_id` ASC),
  CONSTRAINT `fk_software_component_processes1`
    FOREIGN KEY (`process_id`)
    REFERENCES `4pt`.`processes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4pt`.`test_report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `4pt`.`test_report` ;

CREATE TABLE IF NOT EXISTS `4pt`.`test_report` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `process_id` INT UNSIGNED NOT NULL,
  `resume` TEXT NULL DEFAULT NULL,
  `test_case` TEXT NULL DEFAULT NULL,
  `tester_id` INT UNSIGNED NULL,
  `defect_level` TEXT NULL DEFAULT NULL,
  `affected_functions` TEXT NULL DEFAULT NULL,
  `origin_date` DATETIME NULL DEFAULT NULL,
  `resolution_date` DATETIME NULL DEFAULT NULL,
  `solver_id` INT UNSIGNED NULL,
  `sent` TINYINT(1) NULL DEFAULT NULL,
  `project_manager_validated` TINYINT(1) NULL DEFAULT NULL,
  `technical_leader_validated` TINYINT(1) NULL DEFAULT NULL,
  `change_request` TINYINT(1) NULL DEFAULT NULL,
  `change_request_details` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_test_report_processes1_idx` (`process_id` ASC),
  INDEX `fk_test_report_people1_idx` (`tester_id` ASC),
  INDEX `fk_test_report_people2_idx` (`solver_id` ASC),
  CONSTRAINT `fk_test_report_processes1`
    FOREIGN KEY (`process_id`)
    REFERENCES `4pt`.`processes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_test_report_people1`
    FOREIGN KEY (`tester_id`)
    REFERENCES `4pt`.`people` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_test_report_people2`
    FOREIGN KEY (`solver_id`)
    REFERENCES `4pt`.`people` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4pt`.`risks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `4pt`.`risks` ;

CREATE TABLE IF NOT EXISTS `4pt`.`risks` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_plan_id` INT UNSIGNED NOT NULL,
  `title` TEXT NULL,
  `risk` TEXT NULL,
  `cost` DOUBLE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_risks_project_plan1_idx` (`project_plan_id` ASC),
  CONSTRAINT `fk_risks_project_plan1`
    FOREIGN KEY (`project_plan_id`)
    REFERENCES `4pt`.`project_plan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `4pt`.`user_manual`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `4pt`.`user_manual` ;

CREATE TABLE IF NOT EXISTS `4pt`.`user_manual` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `process_id` INT UNSIGNED NOT NULL,
  `user_procedure` TEXT NULL,
  `installation_procedure` TEXT NULL,
  `product_description` TEXT NULL,
  `provided_resources` TEXT NULL,
  `required_enviroment` TEXT NULL,
  `problems_report` TEXT NULL,
  `enter_procedure` TEXT NULL,
  `messages` TEXT NULL,
  `sent` TINYINT(1) NULL DEFAULT NULL,
  `project_manager_validated` TINYINT(1) NULL DEFAULT NULL,
  `technical_leader_validated` TINYINT(1) NULL DEFAULT NULL,
  `change_request` TINYINT(1) NULL DEFAULT NULL,
  `change_request_details` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_manual_processes1_idx` (`process_id` ASC),
  CONSTRAINT `fk_user_manual_processes1`
    FOREIGN KEY (`process_id`)
    REFERENCES `4pt`.`processes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `4pt`.`act_of_acceptance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `4pt`.`act_of_acceptance` ;

CREATE TABLE IF NOT EXISTS `4pt`.`act_of_acceptance` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `process_id` INT UNSIGNED NOT NULL,
  `register` TEXT NULL DEFAULT NULL,
  `date` DATETIME NULL DEFAULT NULL,
  `delivered_items` TEXT NULL DEFAULT NULL,
  `criteria_verification` TEXT NULL DEFAULT NULL,
  `pending_issues` TEXT NULL DEFAULT NULL,
  `client_validated` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_act_of_acceptance_process1_idx` (`process_id` ASC),
  CONSTRAINT `fk_act_of_acceptance_process1`
    FOREIGN KEY (`process_id`)
    REFERENCES `4pt`.`processes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
